# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "wordfilter"
  s.version = "1.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Muhammad Rahmatullah"]
  s.date = "2013-05-30"
  s.description = " Obscenity is a profanity filter gem for Ruby/Rubinius, Rails (through ActiveModel), and Rack middleware "
  s.email = "rahmatthea5@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".gitignore",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "config/blacklist.yml",
    "config/international.yml",
    "lib/badwords.json",
    "lib/wordfilter.js",
    "lib/wordfilter.php",
    "lib/wordfilter.py",
    "lib/wordfilter.rb",
    "wordfilter.gemspec",
    "test/wordfilter_test.js",
    "test/wordfilter_test.php",
    "test/wordfilter_test.py",
    "test/wordfilter_test.rb"
  ]
  s.homepage = "http://github.com/rahmatullah5/worldfilter"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "A small module meant for use in text generators that lets you filter strings for bad words. "


  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
